### ISSUE TITLE
Rename repo to vim-slime-syntax to avoid collision with existing plugin named `vim-slime`

### ISSUE THREAD

**Issue by lpil** [slime-lang/vim-slime-syntax#1]
Ping @doomspork

**Comment by doomspork** [comment]
Wow this is awesome.  Nice work @lpil.  I'm on-board renaming it.

**Comment by lpil** [comment]
I don't seem to be able to do it, can you?

**Comment by doomspork** [comment]
I changed your permissions, let me know if you can update it now.

**Comment by lpil** [comment]
Thanks!
